// MVP開発用ダミーデータ（Supabase接続エラー時のフォールバック用）
import type { ShopWithRelations } from "@/types/database";

/*
 * ダミーデータ ↔ DBスキーマ 対応関係:
 *
 * [shops テーブル]
 * - hours: string → DB は jsonb（シードでは文字列をそのまま保存）
 * - holidays: 旧 closed_days → DB は holidays
 *
 * [stories テーブル]
 * - body: 旧 content → DB は body（Markdown）
 * - summary: 旧 short_content → DB は summary（50文字以内、OGP用）
 * - 削除: story_type, sns_summary, updated_at, ai_interview_id
 * - 追加: key_quotes, emotion_tags, story_themes（ダミーでは null）
 *
 * [menus テーブル]
 * - photo_url: 旧 image_url → DB は photo_url
 * - 削除: sort_order
 * - 追加: eating_tip, kodawari_tags, is_ai_generated（ダミーでは null/false）
 */

export const DUMMY_SHOPS: ShopWithRelations[] = [
  {
    id: "shop-1",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    name: "蔵前 手打ちそば やまと",
    slug: "kuramae-yamato",
    category: "そば・うどん",
    area: "蔵前",
    address: "東京都台東区蔵前3-1-1",
    phone: "03-1234-5678",
    hours: "11:00〜15:00 / 17:00〜21:00",
    holidays: "毎週月曜日",
    description: "創業45年、三代続く手打ちそばの名店。",
    image_url: "/images/shops/shop1-soba.jpg",
    owner_image_url: null,
    owner_name: "山田太郎",
    owner_real_name: null,
    is_published: true,
    address_prefecture: null,
    address_city: null,
    address_street: null,
    address_building: null,
    tabelog_url: null,
    gmb_url: null,
    website_url: null,
    stories: [
      {
        id: "story-1",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-1",
        title: "祖父から受け継いだ石臼と、朝4時の仕込み",
        body: "毎朝4時に起きて、祖父の代から使い続けている石臼でそば粉を挽く。機械のほうが早いことはわかっている。でも、この石臼で挽いた粉には、機械では出せない風味がある。\n\n祖父がこの店を始めたのは昭和56年。当時、蔵前にはまだ多くの職人町が残っていた。「職人の町には、職人が打つそばがなきゃいけない」——それが祖父の口癖だった。\n\n父の代で一度、効率化のために電動の石臼に替えようとしたことがある。でも常連のお客さんが「味が変わった」と言った。たった一人のその声で、父は翌日には元の石臼に戻した。\n\n私が店を継いで10年。毎朝4時に起きるのは正直きつい。でも、石臼をゆっくり回しながらそば粉を挽いている時間が、一日の中で一番好きな時間だ。粉の香りが立ち上る瞬間、祖父と父と、同じ時間を過ごしている気がする。\n\n「おいしい」と言ってもらえることが一番嬉しい。でもそれ以上に、「なんか落ち着くね、この店」と言ってもらえると、祖父から受け継いだものがちゃんと伝わっているんだと思える。",
        summary: "毎朝4時、祖父から受け継いだ石臼でそば粉を挽く。効率より風味。三代続くこだわりが、「なんか落ち着くね」という言葉に変わる瞬間が、一番嬉しい。",
        key_quotes: null,
        emotion_tags: null,
        story_themes: { origin: 5, food_craft: 5, community: 3, hospitality: 3, personality: 4, local_connection: 4, vision: 2 },
        catchcopy_primary: "祖父の石臼、朝4時の誓い",
        catchcopy_alt_1: null,
        catchcopy_alt_2: null,
        highlight: null,
        hook_sentence: "毎朝4時、石臼の音で一日が始まる。三代続くこだわりの蕎麦。",
        status: "published",
        published_at: "2026-03-01T00:00:00Z",
      },
    ],
    menus: [
      {
        id: "menu-1",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-1",
        name: "もりそば",
        price: 850,
        description: "石臼挽き十割そば",
        kodawari_text: "つゆは本枯節と昆布の一番出汁",
        owner_message:
          "まずはこれだけを食べてほしい。祖父の石臼で挽いた十割そばを、何もつけずにひと口。小麦粉でごまかしていない、そば本来の甘みと香りがわかるはずです。つゆは本枯節と利尻昆布の一番出汁。そばをちょっとだけつけて、すすってください。45年間、毎朝4時に起きて守ってきた味です。",
        photo_url: "/images/shops/shop1-soba.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
      {
        id: "menu-2",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-1",
        name: "鴨南蛮そば",
        price: 1600,
        description: "冬季限定・千葉県産合鴨使用",
        kodawari_text: "脂の甘みとそばの香りの調和",
        owner_message:
          "冬だけのお楽しみ。千葉の農家さんから直接仕入れる合鴨は、脂に甘みがあって、温かいそばつゆとの相性が抜群なんです。父の代から「冬はこれ」と決めている一品。寒い日に食べると、体だけじゃなく心まで温まる——そんなそばを目指しています。",
        photo_url: "/images/shops/menu-duck-soba.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
    ],
    _count: { oshi: 24, empathy: 156 },
    basic_info: { id: "bi-1", shop_id: "shop-1", nearest_station: "蔵前駅", walking_minutes: 3, latitude: 35.7014, longitude: 139.7927, budget_lunch_min: null, budget_lunch_max: null, budget_dinner_min: null, budget_dinner_max: null, budget_label_lunch: "casual", budget_label_dinner: "everyday", genre_primary: "そば・うどん", genre_secondary: null, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
    fan_club_plan: { id: "fc-1", shop_id: "shop-1", plan_name: "ライトプラン", price: 300, description: "お店の最新情報をいちはやくキャッチ", benefits: ["限定メッセージ", "裏メニュー情報"], template_base: "light", is_active: true, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  },
  {
    id: "shop-2",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    name: "清澄白河 ビストロ Lien",
    slug: "kiyosumi-lien",
    category: "フレンチ",
    area: "清澄白河",
    address: "東京都江東区清澄2-5-3",
    phone: "03-2345-6789",
    hours: "11:30〜14:00 / 18:00〜22:00",
    holidays: "毎週水曜日",
    description: "パリの路地裏ビストロのような温かさを、清澄白河で。",
    image_url: "/images/shops/shop2-bistro.jpg",
    owner_image_url: null,
    owner_name: "佐藤美咲",
    owner_real_name: null,
    is_published: true,
    address_prefecture: null,
    address_city: null,
    address_street: null,
    address_building: null,
    tabelog_url: null,
    gmb_url: null,
    website_url: null,
    stories: [
      {
        id: "story-2",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-2",
        title: "パリの小さなビストロで学んだ「おばあちゃんの味」",
        body: "フランス料理というと敷居が高いイメージがあるかもしれない。でも私がパリで出会ったのは、近所のおばあちゃんが作るような、素朴で温かい料理だった。\n\n修業先のビストロは、パリ11区の路地裏にあった。シェフのマダム・デュポンは70歳を超えていたが、毎朝マルシェで野菜を選び、その日の気分でメニューを決めた。「レシピ？ そんなものはないわよ。素材と話すのよ」──彼女の口癖だった。\n\n帰国して清澄白河に店を構えたのは、この街の空気がパリ11区に似ていたから。倉庫をリノベしたカフェや、若い作家のギャラリーが点在する街並みに、マダムのビストロが重なった。\n\nうちのメニューは毎日変わる。朝、市場で出会った食材で作る。お客さんには「今日のおすすめは？」ではなく「今日は何があるの？」と聞いてもらいたい。その会話から始まる食事が、私の思い描くビストロの姿だ。",
        summary: "パリの路地裏で70歳のマダムに学んだのは、レシピではなく「素材と話す」こと。清澄白河で毎日メニューが変わるビストロを営む理由。",
        key_quotes: null,
        emotion_tags: null,
        story_themes: { origin: 4, food_craft: 4, community: 2, hospitality: 5, personality: 5, local_connection: 3, vision: 3 },
        catchcopy_primary: "素材と話す、パリ仕込みの一皿",
        catchcopy_alt_1: null,
        catchcopy_alt_2: null,
        highlight: null,
        hook_sentence: "パリの路地裏で70歳のマダムに学んだ「レシピのない料理」。",
        status: "published",
        published_at: "2026-03-01T00:00:00Z",
      },
    ],
    menus: [
      {
        id: "menu-4",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-2",
        name: "本日のランチコース",
        price: 2200,
        description: "前菜・メイン・デザート",
        kodawari_text: "毎朝市場で仕入れた食材で構成",
        owner_message:
          "メニューは毎日変わります。朝、築地の市場で「今日はこの子だ」と思った食材だけを買って帰ります。パリの師匠マダム・デュポンの口癖は「レシピなんてないわよ。素材と話すのよ」。だから私も、食材と相談しながらその日のコースを決めます。何が出るかは来てのお楽しみ。でも、ハズレはありません。",
        photo_url: "/images/shops/menu-lunch-course.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
    ],
    _count: { oshi: 18, empathy: 203 },
    basic_info: { id: "bi-2", shop_id: "shop-2", nearest_station: "清澄白河駅", walking_minutes: 5, latitude: 35.6807, longitude: 139.7990, budget_lunch_min: null, budget_lunch_max: null, budget_dinner_min: null, budget_dinner_max: null, budget_label_lunch: "everyday", budget_label_dinner: "special", genre_primary: "フレンチ", genre_secondary: "ビストロ", created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  },
  {
    id: "shop-3",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    name: "代々木上原 炭火焼鳥 とり信",
    slug: "yoyogi-torishin",
    category: "焼鳥",
    area: "代々木上原",
    address: "東京都渋谷区上原1-22-5",
    phone: "03-3456-7890",
    hours: "17:00〜23:00",
    holidays: "毎週日曜・祝日",
    description: "備長炭にこだわる、本格炭火焼鳥。",
    image_url: "/images/shops/shop3-yakitori.jpg",
    owner_image_url: null,
    owner_name: "中村信一",
    owner_real_name: null,
    is_published: true,
    address_prefecture: null,
    address_city: null,
    address_street: null,
    address_building: null,
    tabelog_url: null,
    gmb_url: null,
    website_url: null,
    stories: [
      {
        id: "story-3",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-3",
        title: "備長炭だけは、絶対に妥協しない理由",
        body: "焼鳥屋にとって炭は命。ガスのほうが温度管理は楽だけど、備長炭でじっくり焼いた鶏肉の、あの皮のパリッとした食感と中のジューシーさは、ガスでは絶対に出せない。\n\n紀州備長炭を使い始めて15年。最初は炭の扱いがわからなくて、何度も火傷した。先代の親方に「炭と友達になれ」と言われて意味がわからなかったけど、今ならわかる。炭には機嫌がある。湿度や気温で燃え方が変わる。その日の炭の状態を見て、焼き加減を調整する。\n\n鶏肉は、宮崎県の契約農家から直送してもらっている。銘柄鶏ではない。でも、餌にこだわり、運動させ、ストレスなく育てた鶏は、どんな銘柄鶏にも負けない旨味がある。農家さんの名前は中西さん。年に2回、必ず農場を訪ねる。\n\n「うまい焼鳥」を出すのは当たり前。その先にあるのは、炭と鶏と、作り手の気持ちが一体になる瞬間。その瞬間を目指して、今日も炭を起こす。",
        summary: "備長炭15年、火傷の数だけ「炭の機嫌」がわかるようになった。宮崎の農家・中西さんの鶏と、炭と、気持ちが一つになる瞬間を目指して。",
        key_quotes: null,
        emotion_tags: null,
        story_themes: { origin: 3, food_craft: 5, community: 2, hospitality: 3, personality: 4, local_connection: 2, vision: 3 },
        catchcopy_primary: "炭と鶏と、15年の真剣勝負",
        catchcopy_alt_1: null,
        catchcopy_alt_2: null,
        highlight: null,
        hook_sentence: "備長炭の機嫌を読み、宮崎の農家から届く鶏と向き合う。",
        status: "published",
        published_at: "2026-03-01T00:00:00Z",
      },
    ],
    menus: [
      {
        id: "menu-6",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-3",
        name: "レバー（塩）",
        price: 250,
        description: "朝〆レバーのレア焼き",
        kodawari_text: "備長炭で低温じっくり仕上げ",
        owner_message:
          "うちに来たら、まずこれを食べてほしい。朝〆の新鮮なレバーを、備長炭で低温でじっくり焼く。中はレアのトロッとした仕上がり。これが食べられるのは、宮崎の中西さんの鶏だからこそ。餌にこだわり、ストレスなく育った鶏のレバーは臭みがまったくない。塩だけで食べてみてください。レバーの概念が変わります。",
        photo_url: "/images/shops/menu-liver.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
      {
        id: "menu-7",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-3",
        name: "おまかせ8本コース",
        price: 2800,
        description: "その日の仕入れで構成する串8本",
        kodawari_text: "塩は粟国の塩、タレは継ぎ足し15年",
        owner_message:
          "迷ったらこれ。その日一番いい部位を8本選んで、塩とタレを交互にお出しします。塩は沖縄・粟国島の天然塩。タレは15年継ぎ足してきた秘伝のもの。順番にも意味があって、最初は淡白な部位から始めて、最後に脂の乗ったものへ。一本一本が、炭と鶏との真剣勝負です。",
        photo_url: "/images/shops/shop3-yakitori.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
    ],
    _count: { oshi: 31, empathy: 189 },
    basic_info: { id: "bi-3", shop_id: "shop-3", nearest_station: "代々木上原駅", walking_minutes: 4, latitude: 35.6690, longitude: 139.6780, budget_lunch_min: null, budget_lunch_max: null, budget_dinner_min: null, budget_dinner_max: null, budget_label_lunch: null, budget_label_dinner: "everyday", genre_primary: "焼鳥", genre_secondary: null, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
    fan_club_plan: { id: "fc-3", shop_id: "shop-3", plan_name: "スタンダードプラン", price: 980, description: "お店との特別なつながりを楽しむ", benefits: ["限定メッセージ", "裏メニュー情報", "予約優先権", "限定イベント参加"], template_base: "standard", is_active: true, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  },
  {
    id: "shop-4",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    name: "三軒茶屋 スパイスカレー MANTRA",
    slug: "sangenjaya-mantra",
    category: "その他",
    area: "三軒茶屋",
    address: "東京都世田谷区三軒茶屋2-14-8",
    phone: "03-4567-8901",
    hours: "11:30〜15:00 / 18:00〜21:00",
    holidays: "不定休",
    description: "インドとスリランカを旅して見つけた、自分だけのスパイス。",
    image_url: "/images/shops/shop4-curry.jpg",
    owner_image_url: null,
    owner_name: "高橋健太",
    owner_real_name: null,
    is_published: true,
    address_prefecture: null,
    address_city: null,
    address_street: null,
    address_building: null,
    tabelog_url: null,
    gmb_url: null,
    website_url: null,
    stories: [
      {
        id: "story-4",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-4",
        title: "会社を辞めてインドへ。スパイスに人生を賭けた日",
        body: "30歳の誕生日に、IT企業を辞めた。「何をやりたいかわからない」まま飛び込んだインドで、路上のカレー屋台に衝撃を受けた。\n\nたった3種類のスパイスで、あんなに複雑な味が出せるのか。おばちゃんが石臼でスパイスを挽く姿は、まるで魔法使いのようだった。\n\n3ヶ月インドに滞在し、その後スリランカへ。現地の家庭を訪ね歩き、おばちゃんたちにカレーの作り方を教わった。レシピは教えてくれない。「見て覚えなさい」と。だから必死で見た。匂いを嗅いだ。手の動きを真似した。\n\n帰国後、三軒茶屋の6坪の物件で開業。最初の1年は赤字だった。でも、一人、また一人と「このカレー、他にない味だね」と言ってくれるお客さんが増えていった。\n\nスパイスは毎月インドから直輸入している。現地の農家と直接やりとりして、収穫時期を指定する。同じスパイスでも、収穫時期で香りがまるで違うから。",
        summary: "IT企業を30歳で辞め、インドの路上カレーに衝撃を受けた。3種のスパイスで生まれる複雑な味。現地のおばちゃんに「見て覚えなさい」と教わった日々。",
        key_quotes: null,
        emotion_tags: null,
        story_themes: { origin: 5, food_craft: 4, community: 3, hospitality: 2, personality: 5, local_connection: 2, vision: 4 },
        catchcopy_primary: "3種のスパイスが生む、無限の味",
        catchcopy_alt_1: null,
        catchcopy_alt_2: null,
        highlight: null,
        hook_sentence: "IT企業を辞め、インドの路上カレーに人生を賭けた男の一皿。",
        status: "published",
        published_at: "2026-03-01T00:00:00Z",
      },
    ],
    menus: [
      {
        id: "menu-8",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-4",
        name: "あいがけカレー",
        price: 1500,
        description: "日替わり2種のカレーを一皿で",
        kodawari_text: "インド直輸入スパイス、収穫時期指定",
        owner_message:
          "2種のカレーを一皿に盛って、少しずつ混ぜながら食べてほしい。右はスリランカ式のサラッとしたカレー、左はインド式のこってりしたカレー。混ぜるたびに味が変わる。最後の一口まで飽きない。スパイスはインドから毎月直輸入していて、収穫時期まで指定しています。同じクミンでも、6月に収穫したものと10月のものでは香りがまるで違うんです。インドの路上で衝撃を受けた「たった3種のスパイスで生まれる複雑さ」を、この一皿で感じてもらえたら。",
        photo_url: "/images/shops/shop4-curry.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
    ],
    _count: { oshi: 42, empathy: 278 },
    basic_info: { id: "bi-4", shop_id: "shop-4", nearest_station: "三軒茶屋駅", walking_minutes: 6, latitude: 35.6433, longitude: 139.6706, budget_lunch_min: null, budget_lunch_max: null, budget_dinner_min: null, budget_dinner_max: null, budget_label_lunch: "everyday", budget_label_dinner: "everyday", genre_primary: "カレー", genre_secondary: "エスニック", created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  },
  {
    id: "shop-5",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    name: "神楽坂 日本料理 つきしろ",
    slug: "kagurazaka-tsukishiro",
    category: "和食",
    area: "神楽坂",
    address: "東京都新宿区神楽坂4-2-1",
    phone: "03-5678-9012",
    hours: "17:00〜22:00",
    holidays: "毎週日曜・月曜",
    description: "季節を映す、一期一会の料理。",
    image_url: "/images/shops/shop5-washoku.jpg",
    owner_image_url: null,
    owner_name: "月城紘子",
    owner_real_name: null,
    is_published: true,
    address_prefecture: null,
    address_city: null,
    address_street: null,
    address_building: null,
    tabelog_url: null,
    gmb_url: null,
    website_url: null,
    stories: [
      {
        id: "story-5",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-5",
        title: "「女に和食は無理だ」と言われた日から",
        body: "料理学校を卒業して最初に入った日本料理店で、親方に言われた。「女に和食は無理だ」と。\n\n悔しかった。でも、辞めなかった。誰よりも早く店に行き、誰よりも遅くまで残った。3年目に初めて刺身を引かせてもらえた時、手が震えた。\n\n独立したのは35歳。神楽坂の路地裏に8席だけの店を構えた。「つきしろ」は月の白い光のこと。派手さはないけれど、静かに照らすような料理を作りたいと思った。\n\nうちの料理は、引き算の料理。素材の味を最大限に引き出すために、余計なものを足さない。出汁は利尻昆布と本枯節だけ。調味料は塩と薄口醤油と味醂。それだけで十分、素材は語ってくれる。\n\n今でもたまに思い出す。「女に和食は無理だ」というあの言葉を。でも今は、あの言葉があったから今の自分がある、と思えるようになった。",
        summary: "「女に和食は無理だ」——その言葉を跳ね返すために包丁を握り続けた。神楽坂8席の「つきしろ」で、引き算の料理を作り続ける理由。",
        key_quotes: null,
        emotion_tags: null,
        story_themes: { origin: 4, food_craft: 5, community: 2, hospitality: 4, personality: 5, local_connection: 3, vision: 4 },
        catchcopy_primary: "引き算の美学、8席の覚悟",
        catchcopy_alt_1: null,
        catchcopy_alt_2: null,
        highlight: null,
        hook_sentence: "「女に和食は無理だ」。その言葉を跳ね返す、引き算の料理。",
        status: "published",
        published_at: "2026-03-01T00:00:00Z",
      },
    ],
    menus: [
      {
        id: "menu-10",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-5",
        name: "おまかせコース",
        price: 12000,
        description: "季節の食材を使った8品のコース",
        kodawari_text: "利尻昆布と本枯節のみの出汁",
        owner_message:
          "私の料理は「引き算」です。出汁は利尻昆布と本枯節だけ。調味料は塩と薄口醤油と味醂。それだけで十分、素材が語ってくれます。8品のコースは、その日の市場で出会った食材で構成します。春なら筍と初鰹、夏なら鱧と万願寺唐辛子。季節を食べる、ということを感じていただけたら。「女に和食は無理」と言われた日から、ずっとこの引き算の料理を磨いてきました。余計なものを足さない勇気——それが私の料理です。",
        photo_url: "/images/shops/shop5-washoku.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
    ],
    _count: { oshi: 15, empathy: 312 },
    basic_info: { id: "bi-5", shop_id: "shop-5", nearest_station: "神楽坂駅", walking_minutes: 2, latitude: 35.7037, longitude: 139.7410, budget_lunch_min: null, budget_lunch_max: null, budget_dinner_min: null, budget_dinner_max: null, budget_label_lunch: null, budget_label_dinner: "celebration", genre_primary: "和食", genre_secondary: null, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
    fan_club_plan: { id: "fc-5", shop_id: "shop-5", plan_name: "プレミアムプラン", price: 2000, description: "いちばんの応援者として特別な体験を", benefits: ["限定メッセージ", "裏メニュー情報", "予約優先権", "限定イベント参加", "店主との交流会", "記念日サプライズ", "特別体験への招待"], template_base: "premium", is_active: true, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  },
  {
    id: "shop-6",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    name: "蔵前 ベーカリー KOKU",
    slug: "kuramae-koku",
    category: "パン",
    area: "蔵前",
    address: "東京都台東区蔵前4-8-2",
    phone: null,
    hours: "8:00〜18:00（売切次第終了）",
    holidays: "毎週火曜・水曜",
    description: "国産小麦と自家製酵母だけで焼く、毎日のパン。",
    image_url: "/images/shops/shop6-bread.jpg",
    owner_image_url: null,
    owner_name: "小林穀",
    owner_real_name: null,
    is_published: true,
    address_prefecture: null,
    address_city: null,
    address_street: null,
    address_building: null,
    tabelog_url: null,
    gmb_url: null,
    website_url: null,
    stories: [
      {
        id: "story-6",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-6",
        title: "パン1個に3日かける理由を、誰も聞いてくれなかった",
        body: "うちのパンは、仕込みから焼き上がりまで3日かかる。自家製酵母の発酵に時間をかけるから。\n\n大手ベーカリーにいた頃は、イーストを使って3時間で焼いていた。効率は良い。でも、何か物足りなかった。自分で酵母を育て始めてわかった。時間をかけた分だけ、小麦の甘みが引き出される。\n\n蔵前に店を出して最初の1年、来るお客さんはみんな「おいしいね」と言ってくれた。嬉しかった。でも、3日かけている意味を聞いてくれる人はいなかった。\n\nそれでいい、味でわかってもらえれば、と思っていた。でも本音は、この3日間の工程を知ってほしかった。酵母が元気に泡立つ瞬間、生地が膨らんでいく過程、焼き上がりの香り——全部含めて、うちのパンだから。\n\n最近、常連さんが一人、「なんでこんなに時間かけてるの？」と聞いてくれた。嬉しくて、30分くらい話してしまった。",
        summary: "パン1個に3日。自家製酵母の発酵に時間をかける理由を誰も聞いてくれなかった。ある常連客の質問で、30分語ってしまった日。",
        key_quotes: null,
        emotion_tags: null,
        story_themes: { origin: 4, food_craft: 5, community: 4, hospitality: 3, personality: 5, local_connection: 4, vision: 3 },
        catchcopy_primary: "パン1個に3日。酵母との対話",
        catchcopy_alt_1: null,
        catchcopy_alt_2: null,
        highlight: null,
        hook_sentence: "自家製酵母の発酵に3日。その理由を聞いてくれた常連さんに感謝。",
        status: "published",
        published_at: "2026-03-01T00:00:00Z",
      },
    ],
    menus: [
      {
        id: "menu-11",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-6",
        name: "カンパーニュ",
        price: 680,
        description: "看板商品・3日間長時間発酵",
        kodawari_text: "北海道産「春よ恋」と自家製酵母",
        owner_message:
          "これがうちの看板です。北海道産小麦「春よ恋」と、自分で育てた酵母だけで焼いています。仕込みから焼き上がりまで3日。大手ベーカリーにいた頃はイーストで3時間だった。でも、3日かけて酵母にゆっくり働いてもらうと、小麦の甘みが全然違う。焼きたてをちぎって、まずは何もつけずに食べてみてください。噛むほどに甘みが広がるはずです。この3日間の工程を、いつか誰かに聞いてほしかった。",
        photo_url: "/images/shops/shop6-bread.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
      {
        id: "menu-12",
        created_at: "2026-03-01T00:00:00Z",
        shop_id: "shop-6",
        name: "クロワッサン",
        price: 380,
        description: "北海道産発酵バター27層",
        kodawari_text: "毎朝5時から成形",
        owner_message:
          "毎朝5時に起きて、一つずつ手で成形しています。北海道産の発酵バターを27層に折り込む。層の数が多すぎても少なすぎてもダメ。27層が、サクッとした食感とバターの香りのベストバランス。焼きたてを割ると、バターの香りがふわっと広がります。売り切れ次第終了なので、早めに来ていただけると嬉しいです。",
        photo_url: "/images/shops/menu-croissant.jpg",
        eating_tip: null,
        kodawari_tags: null,
        is_ai_generated: false,
      },
    ],
    _count: { oshi: 56, empathy: 341 },
    basic_info: { id: "bi-6", shop_id: "shop-6", nearest_station: "蔵前駅", walking_minutes: 5, latitude: 35.7024, longitude: 139.7940, budget_lunch_min: null, budget_lunch_max: null, budget_dinner_min: null, budget_dinner_max: null, budget_label_lunch: "casual", budget_label_dinner: null, genre_primary: "パン", genre_secondary: null, created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-01T00:00:00Z" },
  },
];

// ヘルパー関数
export function getShopBySlug(slug: string): ShopWithRelations | undefined {
  return DUMMY_SHOPS.find((s) => s.slug === slug);
}

export function getShopsByArea(area: string): ShopWithRelations[] {
  return DUMMY_SHOPS.filter((s) => s.area === area);
}

export function getShopsByCategory(category: string): ShopWithRelations[] {
  return DUMMY_SHOPS.filter((s) => s.category === category);
}

export function searchShops(query: string): ShopWithRelations[] {
  const q = query.toLowerCase();
  return DUMMY_SHOPS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.area.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.owner_name.toLowerCase().includes(q) ||
      s.stories.some(
        (st) =>
          st.title.toLowerCase().includes(q) ||
          st.body.toLowerCase().includes(q)
      )
  );
}
